src/http/any-catchall/_get-elements.mjs
src/http/any-catchall/_get-module.mjs
src/http/any-catchall/router.mjs

This fixes 2 windows problems by moving to using URLs instead of paths:
1. makes sure string replacements work properly in windows by normalizing all `\\` to `/`.
2. importing via `import('c:\\...')` will blow up because it looks like `c:` is a protocol.
It looks a bit odd because it has to set pathname instead of use the constructor due to `?` or `#` in filepaths.

Use URLs instead of OS specific paths for importing

---

src/http/any-catchall/router.mjs

Currently, user-defined 404 and 500 pages must be .mjs files or they are ignored. This allows them to be specified as 404.html and 500.html.

allow 404 and 500 as .html pages

---

src/http/any-catchall/router.mjs

importTransform takes a `lookup` function, not `map`.
https://github.com/enhance-dev/enhance-import-transform/blob/main/index.mjs#L1
this is currently breaking any script that tries to
```js
import { myAwesomeLib } from '/_static/bundles/the-awesome-lib.mjs'
```

importTransform usage update

---

package-lock.json
src/http/any-catchall/router.mjs
src/http/any-catchall/templates/head.mjs

This PR changes the API of the head component which is a "breaking change"
Users are mainly shielded from this since for most use cases the framework handles the changes.
For users that are customizing the head they will need to adhere to the new api of:
```
export default function Head(state) {
const { req, status, error } = state
return `
...
`
}
```
The API response is merged with the existing keys so users can access data returned from their API route and use that to customize their head tag

Passes API state to head

---

src/http/any-catchall/_backfill-params.mjs
test/backfill-params.mjs

This PR updates the parts filter to only include parts that need to be matched, and changes the offset of the matches index so that the first "match" (the string that was matched) is ignored.

Allow deep path parameters in _backfill-params.mjs (Fixes #19)

---

src/plugins/beginner.js

`@architect/plugin-bundles` now has a sandbox watcher that can be attached to this plugin's hooks into Sandbox lifecycle events.

mount bundles.sandbox.watcher in host plugin

---

src/http/any-catchall/_get-files.mjs
src/http/any-catchall/_get-module.mjs
test/_get-module.mjs
test/mock-apps/app/api/docs/$$.mjs
test/mock-apps/app/pages/docs/index.html
test/mock-apps/app/pages/index.html

Ran into this problem when my app went from this state:
```
app
└── pages
└── index.html
```
to this state:
```
app
├── api 
│   └── docs
│        └── $$.mjs
└── pages 
├── docs
│     └── $$.mjs
└── index.html
```
Hitting the docs catchall works great but then trying to load index.html it errors out with:
```
Error
Directory import '/project/node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall/node_modules/@architect/views/api/' 
is not supported resolving ES modules imported from /project/begin.com/node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall/router.mjs
```
Since the api folder now exists trying to load `pages/index.html` will try to find the corresponding api route which results in a folder, not a file, so the import barfs.
My fix is to ensure that any path …

Guard against directory import

---

src/http/any-catchall/router.mjs

This three line change adds the `req.session` into the store. This is super useful for components that depend on data from the session. The main use case is authentication. I don't want to have to create an API route for every page that needs my account information so the API can read the session and add it to the store. This change makes it automatic.
So a login button could look like:
```javascript
export default function BeginLogin({ html, state }) {
const { store } = state
const { session } = store
const { account } = session
return html`<li>${ account ?
`<a href="/logout">Log Out</a>` :
`<a href="https://github.com/login/oauth/authorize?client_id=${process.env.GITHUB_CLIENT_ID}&scopes=read:user">Log In</a>`}</li>
`
}
```
Signed-off-by: macdonst <simon.macdonald@gmail.com>

Add session to store

---

package.json
src/http/any-catchall/templates/head.mjs

The updated styles helper interface will improve the experience a good bit.  
Also, the output is quieter if the generated CSS file isn't found by helpers (like when a test runs the head.mjs file without Sandbox running)
~~relies on https://github.com/enhance-dev/arc-plugin-styles/pull/7~~

use new plugin-styles 2.2 helpers

---

app/pages/test/$$.mjs
package.json
src/http/any-catchall/_get-elements.mjs
src/http/any-catchall/_get-files.mjs
src/http/any-catchall/_get-module.mjs
src/http/any-catchall/_render.mjs
src/http/any-catchall/_sort-routes.mjs
src/http/any-catchall/index.mjs
src/http/any-catchall/router.mjs
test/_sort-routes.mjs
test/mock-apps/app/api/about.mjs
test/mock-apps/app/api/backup-data.mjs
test/router-alternate-path.mjs
test/router.mjs

This includes an exportable version of the router that can be used in a plugin for instance to have alternate routes that can be overridden in the main routing structure.

WIP: Export Router with alternate file tree

---

src/http/any-catchall/router.mjs

This fixes #56 
The middleware async function returns brotli compressed, base64 body
This PR adds an additional check for whether the state has been created by a middleware handler, and then if it's base64 encoded, sets `state.json` to the correct json value. 
Components with this fix now have the state populated correctly 
(ps - I looked at expanding the tests from yesterday's PR, and noticed that within the test runner the response from a middleware function isn't base64 encoded and content-encoding: br isn't set in the headers.... i'm not entirely sure how best to construct a test that captures this?)

Fix for state being empty when using middleware pattern

---

.gitignore
src/http/any-catchall/_sort-routes.mjs
test/_sort-routes.mjs

The previous route sorting algorithm used floating point math to sort routes. Each part of the route would contribute a decimal value and the overall number would be sorted. This works fine until routes get really deep. At between 15 and 17 levels deep on the route the floating point math breaks down. This did not show up as a problem because almost no routing for real apps is nested that deeply. But the in practice the route includes the local path to the route folder combined with the folder routing. So if you have 10 folders to get to your local API folder and then your app routing adds 5 levels the sorting breaks. 
The fix here is instead of assigning a numeric value weighted by decimal place we add a letter weighted by position so that each route has a string that can then be …

Fix sort algorithm for deeply nested routes

---

src/http/any-catchall/router.mjs
test/mock-async-middleware/app/api/test-redirect.mjs
test/mock-async-middleware/app/pages/test-redirect.html
test/router-async-middleware.mjs

I discovered middleware was not respecting the redirection concept due to `arc.http.async` doing a response formatting that moves the `state.location` to the headers of the response. This was problematic in enhance because the `state.location` never exists after the async combined method is run, and it never checks the headers for it.
The use-case I wanted is for any middleware to handle the `return { location: "/login" }` style termination. This was failing to be respected accordingly.
When I say `arc.http.async` is formatting the Location of the response, I'm referencing this line: https://github.com/architect/functions/blob/ddc43ecbc23f9481a1bb1c039fe4f444bfffcf2a/src/http/_res-fmt.js#L164

Middleware respects redirect

---

src/plugins/beginner.js

Currently this plugin maps `@architect/shared` to the `<PROJECT_DIR>/models` folder. This is a bit confusing as it is not the `<PROJECT_DIR>/app/models` folder we use to share code between Enhance API, elements, pages, etc. 
I've recently run into the need for the `@architect/shared` functionality when needing to add an Architect plugin to my Enhance app and then once again when attempting to share code between my `app` folder and `jobs` folder.
This is a simple change, but a breaking one. Mostly, I'm raising this PR to begin the conversation as to how we should handle `@architect/shared` in an Enhance app.

Rename folder that maps to @architect/shared

---

src/http/get-_public-catchall/index.mjs

Redirect big assets from _public to _static to gain a few MB's of margin for big assets

redirect big ones

---

src/http/any-catchall/router.mjs

If you are requesting a JSON response and have specified an array of functions to run. For example:
```javascript
export const post = [checkAuth, createLink]
```
and your return from the `createLink` function is:
```javascript
return {
session: newSession,
json: { link: result },
location: '/links'
}
```
You expect to get the JSON payload and not be redirected to `/links`. 
This small code change makes it possible.

Middleware location header fix

---

package.json
src/http/any-catchall/router.mjs
test/mock-headers/app/api/index.mjs
test/mock-headers/app/pages/index.html
test/router.mjs

ensure whenever an api route returns `{headers}` that they get passed through to the final request

Fix headers

---

package.json
src/http/any-catchall/router.mjs

This includes some random guy's `header-timers` tool to create timing headers for the server response.
I added 4 obvious (to me) timers. But there is likely an opportunity to add more. Also they can be enabled/disabled per request. If they are disabled, the `timers`' methods just noop.
Also, if a consumer dev is already creating `Server-Timing` headers, this should play nice. Though, I haven't written any tests yet.
Here's a sample from a site with ~35 elements or so and an API call that includes fetching from Dynamo. The first 2 entries are custom timings from the app; the last 4 are the timers added so far in this PR

Add `Server-Timing` headers

---

src/http/any-catchall/_get-preflight.mjs
src/http/any-catchall/router.mjs

> Apologies if I'm missing context here and this was discussed earlier! Already a big fan of the preflight feature.
Make preflight function execution async
I want to talk to a database to fetch the weather (or any cached data) in my preflight function. Currently the preflight result is not awaited.
My app could run the query in each route's API function (which is async ofc), but that would require each route to have an API file.
- add preflight timers - this makes sense if they can be async, could be a perf killer
- remove fingerprint timers - after a couple months of usage, I've never seen this timer exceed 0ms
Yeah in Sandbox, with both async and sync preflight functions. Works as expected. I didn't see an obvious vector to add an automated test.

async Preflight

---

app/api/verbs.mjs
src/http/any-catchall/router.mjs
test/verbs.mjs

Maps DELETE HTTP verb to `destroy` method and adds tests for all the other verbs.

Issue #110: HTTP DELETE does not map to the API destroy method

---

src/http/any-catchall/package.json

I think we were eager to fix the recent hydration issue and included `zlib` in any-catchall package.json. This means consumers will have to install the 12 year old module from npm even though Enhance uses the Node built-in `node:zlib`.
This causes long install times or even install failures (old zlib uses node-waf)
```
✓ Hydrate Hydrated node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall/
| npm i --omit=dev: added 317 packages, and audited 318 packages in 23s
```
This patch removes `zlib` from package.json.
`npm i` for this Lambda goes to ~600ms in my dev env :)

remove zlib from any-catchall package

---

src/http/any-catchall/_get-elements.mjs
test/mock-html-elements/app/elements/html-element.html
test/mock-html-elements/app/pages/test-element.html
test/router-html-element.mjs

The `_get_elements.mjs` file was failing when trying to load a HTML file. `fileURL.pathname` works on UNIX but not windows because it adds and extra `/` at the start of a Windows path, i.e. `/C:/Users/`. Switching to using the file path and not url file path works on both Windows and UNIX.

Fix Windows issue with HTML elements

---

src/http/any-catchall/router.mjs

If you accidentally set a synchronous function as one of your middleware steps an error will be thrown.
```
Oops, something went wrong
TypeError: Cannot destructure property 'content-type' of 'state.headers' as it is undefined.
at Object.api (file:///Users/simonmacdonald/Developer/macdonst/js-quiz/node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall/router.mjs:236:31)
at async lambda (/Users/simonmacdonald/Developer/macdonst/js-quiz/node_modules/@architect/functions/src/http/index.js:37:22)
```
Which is not very helpful. 
With this change the error changes to:
```
Lambda error
Error: Error: Middleware function "isAdmin" for "/admin/" is not an async function. All middleware functions must be "async".
Lambda: @http any /*
Source: …
```

Better error for async middleware
